GET http://localhost:3000/incident HTTP/1.1
###

POST http://localhost:3000/incident HTTP/1.1
Content-Type: application/json

{
    "short_description": "Test from API",
    "description": "Some new test"
}