
### GET All incident records
GET http://localhost:3000/api/record/incident HTTP/1.1

### GET All incident records
GET http://localhost:3000/api/record/task HTTP/1.1

### CREATE a new incident record
POST http://localhost:3000/api/record/incident HTTP/1.1
Content-Type: application/json

{
    "short_description": "Test from API",
    "description": "Some new test"
}

###Create a new Table
POST http://localhost:3000/api/schema HTTP/1.1
Content-Type: application/json

{
    "name": "request",
    "label": "Request",
    "extends": "incident",
    "fields": [
        {
            "name": "item",
            "label": "Catalog Item",
            "type": "string"
        }
    ]
}

###Create a new Entity
POST http://localhost:3000/api/schema HTTP/1.1
Content-Type: application/json

{
    "name": "request",
    "label": "Request",
    "extends": {
        "name": "task",
        "label": "Task"
    },
    "columns": [
        {
            "name": "item",
            "type": "text"
        },
        {
            "name": "requestor",
            "type": "uuid"
        }
    ]
}

### Get Metadata for the incident table 
GET http://localhost:3000/api/schema/incident HTTP/1.1


### BAD Get Metadata for the request table 
GET http://localhost:3000/api/schema/request HTTP/1.1


### Get UI data for the incident table
GET http://localhost:3000/api/ui/incident HTTP/1.1