import {MigrationInterface, QueryRunner} from "typeorm";

export class default1603276877146 implements MigrationInterface {
    name = 'default1603276877146'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "core"."department" DROP CONSTRAINT "FK_4480f5a6a32bf896a705763c33f"`);
        await queryRunner.query(`CREATE TABLE "cmdb"."cmdb_ci" ("guid" uuid NOT NULL DEFAULT uuid_generate_v4(), "created" TIMESTAMP NOT NULL DEFAULT now(), "updated" TIMESTAMP NOT NULL DEFAULT now(), "created_by" character varying(40) NOT NULL, "updated_by" character varying(40) NOT NULL, "class_name" character varying(80) NOT NULL, "update_count" integer NOT NULL DEFAULT 0, "active" boolean NOT NULL DEFAULT true, "name" character varying(255) NOT NULL, "comments" text NOT NULL DEFAULT '', "environment" character varying NOT NULL, "companyGuid" uuid, "supportGroupGuid" uuid, "primaryOwnerGuid" uuid, CONSTRAINT "PK_13796930b9620bf7ff3d4d96424" PRIMARY KEY ("guid"))`);
        await queryRunner.query(`CREATE TABLE "cmdb"."cmdb_hw" ("guid" uuid NOT NULL DEFAULT uuid_generate_v4(), "created" TIMESTAMP NOT NULL DEFAULT now(), "updated" TIMESTAMP NOT NULL DEFAULT now(), "created_by" character varying(40) NOT NULL, "updated_by" character varying(40) NOT NULL, "class_name" character varying(80) NOT NULL, "update_count" integer NOT NULL DEFAULT 0, "active" boolean NOT NULL DEFAULT true, "name" character varying(255) NOT NULL, "comments" text NOT NULL DEFAULT '', "environment" character varying NOT NULL, "serial_number" character varying(255) NOT NULL, "companyGuid" uuid, "supportGroupGuid" uuid, "primaryOwnerGuid" uuid, "manufacturerGuid" uuid, CONSTRAINT "PK_602a5a2f773b4aac435e9f18d67" PRIMARY KEY ("guid"))`);
        await queryRunner.query(`CREATE TABLE "cmdb"."cmdb_hw_computer" ("guid" uuid NOT NULL DEFAULT uuid_generate_v4(), "created" TIMESTAMP NOT NULL DEFAULT now(), "updated" TIMESTAMP NOT NULL DEFAULT now(), "created_by" character varying(40) NOT NULL, "updated_by" character varying(40) NOT NULL, "class_name" character varying(80) NOT NULL, "update_count" integer NOT NULL DEFAULT 0, "active" boolean NOT NULL DEFAULT true, "name" character varying(255) NOT NULL, "comments" text NOT NULL DEFAULT '', "environment" character varying NOT NULL, "serial_number" character varying(255) NOT NULL, "os" text, "companyGuid" uuid, "supportGroupGuid" uuid, "primaryOwnerGuid" uuid, "manufacturerGuid" uuid, CONSTRAINT "PK_9b948c9b5532ff2baf5271e5ba7" PRIMARY KEY ("guid"))`);
        await queryRunner.query(`CREATE TABLE "itsm"."change" ("guid" uuid NOT NULL DEFAULT uuid_generate_v4(), "created" TIMESTAMP NOT NULL DEFAULT now(), "updated" TIMESTAMP NOT NULL DEFAULT now(), "created_by" character varying(40) NOT NULL, "updated_by" character varying(40) NOT NULL, "class_name" character varying(80) NOT NULL, "update_count" integer NOT NULL DEFAULT 0, "active" boolean NOT NULL DEFAULT true, "summary" character varying(255) NOT NULL DEFAULT '', "details" text NOT NULL DEFAULT '', "planned_start" date, "planned_finish" date, "justification" text NOT NULL DEFAULT '', "implementation_plan" text NOT NULL DEFAULT '', "backout_plan" text NOT NULL DEFAULT '', "test_plan" text NOT NULL DEFAULT '', "risk_analysis" text NOT NULL DEFAULT '', "assigneeGuid" uuid, "assignmentGroupGuid" uuid, "authorisedContactGuid" uuid, "parentTaskGuid" uuid, "configItemGuid" uuid, CONSTRAINT "PK_b64eaf240551a6e9f8946458bf4" PRIMARY KEY ("guid"))`);
        await queryRunner.query(`CREATE TABLE "itsm"."change_task" ("guid" uuid NOT NULL DEFAULT uuid_generate_v4(), "created" TIMESTAMP NOT NULL DEFAULT now(), "updated" TIMESTAMP NOT NULL DEFAULT now(), "created_by" character varying(40) NOT NULL, "updated_by" character varying(40) NOT NULL, "class_name" character varying(80) NOT NULL, "update_count" integer NOT NULL DEFAULT 0, "active" boolean NOT NULL DEFAULT true, "summary" character varying(255) NOT NULL DEFAULT '', "details" text NOT NULL DEFAULT '', "assigneeGuid" uuid, "assignmentGroupGuid" uuid, "authorisedContactGuid" uuid, "parentTaskGuid" uuid, "configItemGuid" uuid, "parentChangeGuid" uuid, CONSTRAINT "PK_d84c3ecbb369cc3f327e37894cf" PRIMARY KEY ("guid"))`);
        await queryRunner.query(`CREATE TABLE "itsm"."incident" ("guid" uuid NOT NULL DEFAULT uuid_generate_v4(), "created" TIMESTAMP NOT NULL DEFAULT now(), "updated" TIMESTAMP NOT NULL DEFAULT now(), "created_by" character varying(40) NOT NULL, "updated_by" character varying(40) NOT NULL, "class_name" character varying(80) NOT NULL, "update_count" integer NOT NULL DEFAULT 0, "active" boolean NOT NULL DEFAULT true, "summary" character varying(255) NOT NULL DEFAULT '', "details" text NOT NULL DEFAULT '', "assigneeGuid" uuid, "assignmentGroupGuid" uuid, "authorisedContactGuid" uuid, "parentTaskGuid" uuid, "configItemGuid" uuid, CONSTRAINT "PK_308bd7dd9ee43783b3e2ec4bf06" PRIMARY KEY ("guid"))`);
        await queryRunner.query(`CREATE TABLE "itsm"."incident_task" ("guid" uuid NOT NULL DEFAULT uuid_generate_v4(), "created" TIMESTAMP NOT NULL DEFAULT now(), "updated" TIMESTAMP NOT NULL DEFAULT now(), "created_by" character varying(40) NOT NULL, "updated_by" character varying(40) NOT NULL, "class_name" character varying(80) NOT NULL, "update_count" integer NOT NULL DEFAULT 0, "active" boolean NOT NULL DEFAULT true, "summary" character varying(255) NOT NULL DEFAULT '', "details" text NOT NULL DEFAULT '', "assigneeGuid" uuid, "assignmentGroupGuid" uuid, "authorisedContactGuid" uuid, "parentTaskGuid" uuid, "configItemGuid" uuid, "parentIncidentGuid" uuid, CONSTRAINT "PK_2f8e00e9de0d734364cab0b3f1f" PRIMARY KEY ("guid"))`);
        await queryRunner.query(`ALTER TABLE "core"."department" DROP COLUMN "costCentreGuid"`);
        await queryRunner.query(`ALTER TABLE "system"."dbo" ADD "active" boolean NOT NULL DEFAULT true`);
        await queryRunner.query(`ALTER TABLE "system"."field_label" ADD "active" boolean NOT NULL DEFAULT true`);
        await queryRunner.query(`ALTER TABLE "core"."company" ADD "active" boolean NOT NULL DEFAULT true`);
        await queryRunner.query(`ALTER TABLE "system"."role" ADD "active" boolean NOT NULL DEFAULT true`);
        await queryRunner.query(`ALTER TABLE "core"."department" ADD "active" boolean NOT NULL DEFAULT true`);
        await queryRunner.query(`ALTER TABLE "core"."department" ADD "companyGuid" uuid`);
        await queryRunner.query(`ALTER TABLE "system"."user" ADD "active" boolean NOT NULL DEFAULT true`);
        await queryRunner.query(`ALTER TABLE "system"."user" ADD "companyGuid" uuid`);
        await queryRunner.query(`ALTER TABLE "system"."group" ADD "active" boolean NOT NULL DEFAULT true`);
        await queryRunner.query(`ALTER TABLE "core"."cost_centre" ADD "active" boolean NOT NULL DEFAULT true`);
        await queryRunner.query(`ALTER TABLE "core"."cost_centre" ADD "departmentGuid" uuid`);
        await queryRunner.query(`ALTER TABLE "core"."task" ADD "active" boolean NOT NULL DEFAULT true`);
        await queryRunner.query(`ALTER TABLE "core"."task" ADD "configItemGuid" uuid`);
        await queryRunner.query(`ALTER TABLE "itsm"."sla_definition" ADD "active" boolean NOT NULL DEFAULT true`);
        await queryRunner.query(`ALTER TABLE "itsm"."task_sla" ADD "active" boolean NOT NULL DEFAULT true`);
        await queryRunner.query(`ALTER TABLE "system"."server_script" ADD "active" boolean NOT NULL DEFAULT true`);
        await queryRunner.query(`ALTER TABLE "system"."dictionary" ALTER COLUMN "active" SET DEFAULT true`);
        await queryRunner.query(`ALTER TABLE "core"."department" ADD CONSTRAINT "FK_bd5fd495d9d40bd416d3bd24c7e" FOREIGN KEY ("companyGuid") REFERENCES "core"."company"("guid") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "system"."user" ADD CONSTRAINT "FK_39d46f5408975b627f9a2125765" FOREIGN KEY ("companyGuid") REFERENCES "core"."company"("guid") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "cmdb"."cmdb_ci" ADD CONSTRAINT "FK_4fccf8771c8ab9216d37d762c24" FOREIGN KEY ("companyGuid") REFERENCES "core"."company"("guid") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "cmdb"."cmdb_ci" ADD CONSTRAINT "FK_b577a26eae55fd40c9d44eeef56" FOREIGN KEY ("supportGroupGuid") REFERENCES "system"."group"("guid") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "cmdb"."cmdb_ci" ADD CONSTRAINT "FK_90fcb6ec5c378bd3aa2c9207354" FOREIGN KEY ("primaryOwnerGuid") REFERENCES "system"."user"("guid") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "cmdb"."cmdb_hw" ADD CONSTRAINT "FK_f51ce920754bf2f579ca7466fda" FOREIGN KEY ("companyGuid") REFERENCES "core"."company"("guid") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "cmdb"."cmdb_hw" ADD CONSTRAINT "FK_47914c363ec5301e5138d10ebb5" FOREIGN KEY ("supportGroupGuid") REFERENCES "system"."group"("guid") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "cmdb"."cmdb_hw" ADD CONSTRAINT "FK_f6c7ebe2341c1868949c8ef4ab2" FOREIGN KEY ("primaryOwnerGuid") REFERENCES "system"."user"("guid") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "cmdb"."cmdb_hw" ADD CONSTRAINT "FK_f2b1cf60d608680fd885fce434a" FOREIGN KEY ("manufacturerGuid") REFERENCES "core"."company"("guid") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "cmdb"."cmdb_hw_computer" ADD CONSTRAINT "FK_9ec68b2cccef82c036a2fb34056" FOREIGN KEY ("companyGuid") REFERENCES "core"."company"("guid") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "cmdb"."cmdb_hw_computer" ADD CONSTRAINT "FK_ed8834918d025c21d344bc44a51" FOREIGN KEY ("supportGroupGuid") REFERENCES "system"."group"("guid") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "cmdb"."cmdb_hw_computer" ADD CONSTRAINT "FK_2d4cd3b45a9818382d7afaf8a0d" FOREIGN KEY ("primaryOwnerGuid") REFERENCES "system"."user"("guid") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "cmdb"."cmdb_hw_computer" ADD CONSTRAINT "FK_35b429952c55717d0066d69f26f" FOREIGN KEY ("manufacturerGuid") REFERENCES "core"."company"("guid") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "core"."cost_centre" ADD CONSTRAINT "FK_2782faa9ad3a7e7336628c32416" FOREIGN KEY ("departmentGuid") REFERENCES "core"."department"("guid") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "core"."task" ADD CONSTRAINT "FK_d6bd18732897608eb7645547908" FOREIGN KEY ("configItemGuid") REFERENCES "cmdb"."cmdb_ci"("guid") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "itsm"."change" ADD CONSTRAINT "FK_57a2da03f967eda002ea025245e" FOREIGN KEY ("assigneeGuid") REFERENCES "system"."user"("guid") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "itsm"."change" ADD CONSTRAINT "FK_bcb9bf2d0769a735e9006858649" FOREIGN KEY ("assignmentGroupGuid") REFERENCES "system"."group"("guid") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "itsm"."change" ADD CONSTRAINT "FK_8d68a4cc97dde18001d22a035b0" FOREIGN KEY ("authorisedContactGuid") REFERENCES "system"."user"("guid") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "itsm"."change" ADD CONSTRAINT "FK_fc86c2d6821ae9d3cca3815fce3" FOREIGN KEY ("parentTaskGuid") REFERENCES "core"."task"("guid") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "itsm"."change" ADD CONSTRAINT "FK_8263101ac5df5472dd85dd72ba0" FOREIGN KEY ("configItemGuid") REFERENCES "cmdb"."cmdb_ci"("guid") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "itsm"."change_task" ADD CONSTRAINT "FK_faec56e620f4b71317e9b75b876" FOREIGN KEY ("assigneeGuid") REFERENCES "system"."user"("guid") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "itsm"."change_task" ADD CONSTRAINT "FK_bf1485da08af05a98612f741d6d" FOREIGN KEY ("assignmentGroupGuid") REFERENCES "system"."group"("guid") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "itsm"."change_task" ADD CONSTRAINT "FK_e050c5619aa8f546231eb0c2641" FOREIGN KEY ("authorisedContactGuid") REFERENCES "system"."user"("guid") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "itsm"."change_task" ADD CONSTRAINT "FK_842c85fe9abb6c5b311e74b7a76" FOREIGN KEY ("parentTaskGuid") REFERENCES "core"."task"("guid") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "itsm"."change_task" ADD CONSTRAINT "FK_8ac583c7179d4a7add478788714" FOREIGN KEY ("configItemGuid") REFERENCES "cmdb"."cmdb_ci"("guid") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "itsm"."change_task" ADD CONSTRAINT "FK_7d5d650b9daa3e295813f6261a9" FOREIGN KEY ("parentChangeGuid") REFERENCES "itsm"."change"("guid") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "itsm"."incident" ADD CONSTRAINT "FK_23593b613b7e9937ed786411361" FOREIGN KEY ("assigneeGuid") REFERENCES "system"."user"("guid") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "itsm"."incident" ADD CONSTRAINT "FK_a7b4ddefe141e1403ce9e15c0ad" FOREIGN KEY ("assignmentGroupGuid") REFERENCES "system"."group"("guid") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "itsm"."incident" ADD CONSTRAINT "FK_e1e38bf5bda233b3894c8c2c544" FOREIGN KEY ("authorisedContactGuid") REFERENCES "system"."user"("guid") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "itsm"."incident" ADD CONSTRAINT "FK_74cdaaa369aa67c0eda97ffe302" FOREIGN KEY ("parentTaskGuid") REFERENCES "core"."task"("guid") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "itsm"."incident" ADD CONSTRAINT "FK_fbe43859675e11d00ce02fc641b" FOREIGN KEY ("configItemGuid") REFERENCES "cmdb"."cmdb_ci"("guid") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "itsm"."incident_task" ADD CONSTRAINT "FK_32c5fb59e23324387d1632806b5" FOREIGN KEY ("assigneeGuid") REFERENCES "system"."user"("guid") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "itsm"."incident_task" ADD CONSTRAINT "FK_04d2757010dab9f91e95361775a" FOREIGN KEY ("assignmentGroupGuid") REFERENCES "system"."group"("guid") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "itsm"."incident_task" ADD CONSTRAINT "FK_50ee81d5d59ecd75ed220be7da9" FOREIGN KEY ("authorisedContactGuid") REFERENCES "system"."user"("guid") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "itsm"."incident_task" ADD CONSTRAINT "FK_7ac593792764aee8535d9daf4fc" FOREIGN KEY ("parentTaskGuid") REFERENCES "core"."task"("guid") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "itsm"."incident_task" ADD CONSTRAINT "FK_281b7e330fee99c5fa442288886" FOREIGN KEY ("configItemGuid") REFERENCES "cmdb"."cmdb_ci"("guid") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "itsm"."incident_task" ADD CONSTRAINT "FK_87817a7de289faf870eb3c4ecaa" FOREIGN KEY ("parentIncidentGuid") REFERENCES "itsm"."incident"("guid") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "itsm"."incident_task" DROP CONSTRAINT "FK_87817a7de289faf870eb3c4ecaa"`);
        await queryRunner.query(`ALTER TABLE "itsm"."incident_task" DROP CONSTRAINT "FK_281b7e330fee99c5fa442288886"`);
        await queryRunner.query(`ALTER TABLE "itsm"."incident_task" DROP CONSTRAINT "FK_7ac593792764aee8535d9daf4fc"`);
        await queryRunner.query(`ALTER TABLE "itsm"."incident_task" DROP CONSTRAINT "FK_50ee81d5d59ecd75ed220be7da9"`);
        await queryRunner.query(`ALTER TABLE "itsm"."incident_task" DROP CONSTRAINT "FK_04d2757010dab9f91e95361775a"`);
        await queryRunner.query(`ALTER TABLE "itsm"."incident_task" DROP CONSTRAINT "FK_32c5fb59e23324387d1632806b5"`);
        await queryRunner.query(`ALTER TABLE "itsm"."incident" DROP CONSTRAINT "FK_fbe43859675e11d00ce02fc641b"`);
        await queryRunner.query(`ALTER TABLE "itsm"."incident" DROP CONSTRAINT "FK_74cdaaa369aa67c0eda97ffe302"`);
        await queryRunner.query(`ALTER TABLE "itsm"."incident" DROP CONSTRAINT "FK_e1e38bf5bda233b3894c8c2c544"`);
        await queryRunner.query(`ALTER TABLE "itsm"."incident" DROP CONSTRAINT "FK_a7b4ddefe141e1403ce9e15c0ad"`);
        await queryRunner.query(`ALTER TABLE "itsm"."incident" DROP CONSTRAINT "FK_23593b613b7e9937ed786411361"`);
        await queryRunner.query(`ALTER TABLE "itsm"."change_task" DROP CONSTRAINT "FK_7d5d650b9daa3e295813f6261a9"`);
        await queryRunner.query(`ALTER TABLE "itsm"."change_task" DROP CONSTRAINT "FK_8ac583c7179d4a7add478788714"`);
        await queryRunner.query(`ALTER TABLE "itsm"."change_task" DROP CONSTRAINT "FK_842c85fe9abb6c5b311e74b7a76"`);
        await queryRunner.query(`ALTER TABLE "itsm"."change_task" DROP CONSTRAINT "FK_e050c5619aa8f546231eb0c2641"`);
        await queryRunner.query(`ALTER TABLE "itsm"."change_task" DROP CONSTRAINT "FK_bf1485da08af05a98612f741d6d"`);
        await queryRunner.query(`ALTER TABLE "itsm"."change_task" DROP CONSTRAINT "FK_faec56e620f4b71317e9b75b876"`);
        await queryRunner.query(`ALTER TABLE "itsm"."change" DROP CONSTRAINT "FK_8263101ac5df5472dd85dd72ba0"`);
        await queryRunner.query(`ALTER TABLE "itsm"."change" DROP CONSTRAINT "FK_fc86c2d6821ae9d3cca3815fce3"`);
        await queryRunner.query(`ALTER TABLE "itsm"."change" DROP CONSTRAINT "FK_8d68a4cc97dde18001d22a035b0"`);
        await queryRunner.query(`ALTER TABLE "itsm"."change" DROP CONSTRAINT "FK_bcb9bf2d0769a735e9006858649"`);
        await queryRunner.query(`ALTER TABLE "itsm"."change" DROP CONSTRAINT "FK_57a2da03f967eda002ea025245e"`);
        await queryRunner.query(`ALTER TABLE "core"."task" DROP CONSTRAINT "FK_d6bd18732897608eb7645547908"`);
        await queryRunner.query(`ALTER TABLE "core"."cost_centre" DROP CONSTRAINT "FK_2782faa9ad3a7e7336628c32416"`);
        await queryRunner.query(`ALTER TABLE "cmdb"."cmdb_hw_computer" DROP CONSTRAINT "FK_35b429952c55717d0066d69f26f"`);
        await queryRunner.query(`ALTER TABLE "cmdb"."cmdb_hw_computer" DROP CONSTRAINT "FK_2d4cd3b45a9818382d7afaf8a0d"`);
        await queryRunner.query(`ALTER TABLE "cmdb"."cmdb_hw_computer" DROP CONSTRAINT "FK_ed8834918d025c21d344bc44a51"`);
        await queryRunner.query(`ALTER TABLE "cmdb"."cmdb_hw_computer" DROP CONSTRAINT "FK_9ec68b2cccef82c036a2fb34056"`);
        await queryRunner.query(`ALTER TABLE "cmdb"."cmdb_hw" DROP CONSTRAINT "FK_f2b1cf60d608680fd885fce434a"`);
        await queryRunner.query(`ALTER TABLE "cmdb"."cmdb_hw" DROP CONSTRAINT "FK_f6c7ebe2341c1868949c8ef4ab2"`);
        await queryRunner.query(`ALTER TABLE "cmdb"."cmdb_hw" DROP CONSTRAINT "FK_47914c363ec5301e5138d10ebb5"`);
        await queryRunner.query(`ALTER TABLE "cmdb"."cmdb_hw" DROP CONSTRAINT "FK_f51ce920754bf2f579ca7466fda"`);
        await queryRunner.query(`ALTER TABLE "cmdb"."cmdb_ci" DROP CONSTRAINT "FK_90fcb6ec5c378bd3aa2c9207354"`);
        await queryRunner.query(`ALTER TABLE "cmdb"."cmdb_ci" DROP CONSTRAINT "FK_b577a26eae55fd40c9d44eeef56"`);
        await queryRunner.query(`ALTER TABLE "cmdb"."cmdb_ci" DROP CONSTRAINT "FK_4fccf8771c8ab9216d37d762c24"`);
        await queryRunner.query(`ALTER TABLE "system"."user" DROP CONSTRAINT "FK_39d46f5408975b627f9a2125765"`);
        await queryRunner.query(`ALTER TABLE "core"."department" DROP CONSTRAINT "FK_bd5fd495d9d40bd416d3bd24c7e"`);
        await queryRunner.query(`ALTER TABLE "system"."dictionary" ALTER COLUMN "active" SET DEFAULT false`);
        await queryRunner.query(`ALTER TABLE "system"."server_script" DROP COLUMN "active"`);
        await queryRunner.query(`ALTER TABLE "itsm"."task_sla" DROP COLUMN "active"`);
        await queryRunner.query(`ALTER TABLE "itsm"."sla_definition" DROP COLUMN "active"`);
        await queryRunner.query(`ALTER TABLE "core"."task" DROP COLUMN "configItemGuid"`);
        await queryRunner.query(`ALTER TABLE "core"."task" DROP COLUMN "active"`);
        await queryRunner.query(`ALTER TABLE "core"."cost_centre" DROP COLUMN "departmentGuid"`);
        await queryRunner.query(`ALTER TABLE "core"."cost_centre" DROP COLUMN "active"`);
        await queryRunner.query(`ALTER TABLE "system"."group" DROP COLUMN "active"`);
        await queryRunner.query(`ALTER TABLE "system"."user" DROP COLUMN "companyGuid"`);
        await queryRunner.query(`ALTER TABLE "system"."user" DROP COLUMN "active"`);
        await queryRunner.query(`ALTER TABLE "core"."department" DROP COLUMN "companyGuid"`);
        await queryRunner.query(`ALTER TABLE "core"."department" DROP COLUMN "active"`);
        await queryRunner.query(`ALTER TABLE "system"."role" DROP COLUMN "active"`);
        await queryRunner.query(`ALTER TABLE "core"."company" DROP COLUMN "active"`);
        await queryRunner.query(`ALTER TABLE "system"."field_label" DROP COLUMN "active"`);
        await queryRunner.query(`ALTER TABLE "system"."dbo" DROP COLUMN "active"`);
        await queryRunner.query(`ALTER TABLE "core"."department" ADD "costCentreGuid" uuid`);
        await queryRunner.query(`DROP TABLE "itsm"."incident_task"`);
        await queryRunner.query(`DROP TABLE "itsm"."incident"`);
        await queryRunner.query(`DROP TABLE "itsm"."change_task"`);
        await queryRunner.query(`DROP TABLE "itsm"."change"`);
        await queryRunner.query(`DROP TABLE "cmdb"."cmdb_hw_computer"`);
        await queryRunner.query(`DROP TABLE "cmdb"."cmdb_hw"`);
        await queryRunner.query(`DROP TABLE "cmdb"."cmdb_ci"`);
        await queryRunner.query(`ALTER TABLE "core"."department" ADD CONSTRAINT "FK_4480f5a6a32bf896a705763c33f" FOREIGN KEY ("costCentreGuid") REFERENCES "core"."cost_centre"("guid") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

}
