import {MigrationInterface, QueryRunner} from "typeorm";

export class default1604305398949 implements MigrationInterface {
    name = 'default1604305398949'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE "system"."field_label" ("guid" uuid NOT NULL DEFAULT uuid_generate_v4(), "created" TIMESTAMP NOT NULL DEFAULT now(), "updated" TIMESTAMP NOT NULL DEFAULT now(), "created_by" text NOT NULL, "updated_by" text NOT NULL, "class_name" text NOT NULL, "scope" text NOT NULL, "update_count" integer NOT NULL DEFAULT 0, "active" boolean NOT NULL DEFAULT true, "label" text, "table" text NOT NULL, "elementGuid" uuid NOT NULL, CONSTRAINT "PK_71e8dd10df17990f660cb60560e" PRIMARY KEY ("guid"))`);
        await queryRunner.query(`CREATE TABLE "system"."dictionary" ("guid" uuid NOT NULL DEFAULT uuid_generate_v4(), "created" TIMESTAMP NOT NULL DEFAULT now(), "updated" TIMESTAMP NOT NULL DEFAULT now(), "created_by" text NOT NULL, "updated_by" text NOT NULL, "class_name" text NOT NULL, "scope" text NOT NULL, "update_count" integer NOT NULL DEFAULT 0, "active" boolean NOT NULL DEFAULT true, "primary" boolean NOT NULL DEFAULT false, "read_only" boolean NOT NULL DEFAULT false, "mandatory" boolean NOT NULL DEFAULT false, "display" boolean NOT NULL DEFAULT false, "column_name" text NOT NULL, "column_label" text NOT NULL, "table" text NOT NULL, "type" text NOT NULL, "reference_table" text, "max_length" integer NOT NULL DEFAULT 255, "default_value" text, CONSTRAINT "PK_a154bab24262c7b859e87d18c34" PRIMARY KEY ("guid"))`);
        await queryRunner.query(`CREATE TABLE "system"."server_script" ("guid" uuid NOT NULL DEFAULT uuid_generate_v4(), "created" TIMESTAMP NOT NULL DEFAULT now(), "updated" TIMESTAMP NOT NULL DEFAULT now(), "created_by" text NOT NULL, "updated_by" text NOT NULL, "class_name" text NOT NULL, "scope" text NOT NULL, "update_count" integer NOT NULL DEFAULT 0, "active" boolean NOT NULL DEFAULT true, "name" text NOT NULL, "script" text NOT NULL, "when" text NOT NULL, "on" text NOT NULL, "table" text NOT NULL, "order" integer NOT NULL, CONSTRAINT "PK_37634d2bd85d3a7cfb7d2713c71" PRIMARY KEY ("guid"))`);
        await queryRunner.query(`CREATE TABLE "system"."dbo" ("guid" uuid NOT NULL DEFAULT uuid_generate_v4(), "created" TIMESTAMP NOT NULL DEFAULT now(), "updated" TIMESTAMP NOT NULL DEFAULT now(), "created_by" text NOT NULL, "updated_by" text NOT NULL, "class_name" text NOT NULL, "scope" text NOT NULL, "update_count" integer NOT NULL DEFAULT 0, "active" boolean NOT NULL DEFAULT true, "name" text NOT NULL, "label" text NOT NULL, "extends" text, "autonumber" boolean NOT NULL DEFAULT false, "number_prefix" text, "number_digits" integer, "table_scope" text NOT NULL DEFAULT 'system', CONSTRAINT "UQ_22f9b3b0c6d10fb0093a7e3b18f" UNIQUE ("name"), CONSTRAINT "PK_ddf14391fda1e6d3dac4f563535" PRIMARY KEY ("guid"))`);
        await queryRunner.query(`CREATE TABLE "core"."company" ("guid" uuid NOT NULL DEFAULT uuid_generate_v4(), "created" TIMESTAMP NOT NULL DEFAULT now(), "updated" TIMESTAMP NOT NULL DEFAULT now(), "created_by" text NOT NULL, "updated_by" text NOT NULL, "class_name" text NOT NULL, "scope" text NOT NULL, "update_count" integer NOT NULL DEFAULT 0, "active" boolean NOT NULL DEFAULT true, "name" text NOT NULL, "description" text NOT NULL DEFAULT '', CONSTRAINT "PK_3700606e0851525b59edd40068b" PRIMARY KEY ("guid"))`);
        await queryRunner.query(`CREATE TABLE "system"."acl" ("guid" uuid NOT NULL DEFAULT uuid_generate_v4(), "created" TIMESTAMP NOT NULL DEFAULT now(), "updated" TIMESTAMP NOT NULL DEFAULT now(), "created_by" text NOT NULL, "updated_by" text NOT NULL, "class_name" text NOT NULL, "scope" text NOT NULL, "update_count" integer NOT NULL DEFAULT 0, "active" boolean NOT NULL DEFAULT true, "table" text NOT NULL, "type" text NOT NULL, "operation" text NOT NULL, "fieldGuid" uuid, CONSTRAINT "PK_4bf88b969c77e4606d6a3ad596c" PRIMARY KEY ("guid"))`);
        await queryRunner.query(`CREATE TABLE "system"."role" ("guid" uuid NOT NULL DEFAULT uuid_generate_v4(), "created" TIMESTAMP NOT NULL DEFAULT now(), "updated" TIMESTAMP NOT NULL DEFAULT now(), "created_by" text NOT NULL, "updated_by" text NOT NULL, "class_name" text NOT NULL, "scope" text NOT NULL, "update_count" integer NOT NULL DEFAULT 0, "active" boolean NOT NULL DEFAULT true, "name" text NOT NULL, CONSTRAINT "PK_1ec12177b9098885b982f2f7bd1" PRIMARY KEY ("guid"))`);
        await queryRunner.query(`CREATE TABLE "core"."department" ("guid" uuid NOT NULL DEFAULT uuid_generate_v4(), "created" TIMESTAMP NOT NULL DEFAULT now(), "updated" TIMESTAMP NOT NULL DEFAULT now(), "created_by" text NOT NULL, "updated_by" text NOT NULL, "class_name" text NOT NULL, "scope" text NOT NULL, "update_count" integer NOT NULL DEFAULT 0, "active" boolean NOT NULL DEFAULT true, "name" text NOT NULL, "description" text NOT NULL DEFAULT '', "departmentHeadGuid" uuid, "companyGuid" uuid, CONSTRAINT "PK_64cc30595cc3b9f9d721c4eb1fb" PRIMARY KEY ("guid"))`);
        await queryRunner.query(`CREATE TABLE "system"."user" ("guid" uuid NOT NULL DEFAULT uuid_generate_v4(), "created" TIMESTAMP NOT NULL DEFAULT now(), "updated" TIMESTAMP NOT NULL DEFAULT now(), "created_by" text NOT NULL, "updated_by" text NOT NULL, "class_name" text NOT NULL, "scope" text NOT NULL, "update_count" integer NOT NULL DEFAULT 0, "active" boolean NOT NULL DEFAULT true, "user_name" text NOT NULL, "first_name" text NOT NULL, "last_name" text NOT NULL, "email" text, "name" text NOT NULL, "departmentGuid" uuid, "companyGuid" uuid, CONSTRAINT "UQ_368fd20c10764c99e257662e13c" UNIQUE ("user_name"), CONSTRAINT "PK_421be1c35df3ec77ae5d15f73fc" PRIMARY KEY ("guid"))`);
        await queryRunner.query(`CREATE TABLE "system"."group" ("guid" uuid NOT NULL DEFAULT uuid_generate_v4(), "created" TIMESTAMP NOT NULL DEFAULT now(), "updated" TIMESTAMP NOT NULL DEFAULT now(), "created_by" text NOT NULL, "updated_by" text NOT NULL, "class_name" text NOT NULL, "scope" text NOT NULL, "update_count" integer NOT NULL DEFAULT 0, "active" boolean NOT NULL DEFAULT true, "name" text NOT NULL, "description" text, "managerGuid" uuid, CONSTRAINT "PK_57a8a795270b3d834546a26864c" PRIMARY KEY ("guid"))`);
        await queryRunner.query(`CREATE TABLE "cmdb"."ci" ("guid" uuid NOT NULL DEFAULT uuid_generate_v4(), "created" TIMESTAMP NOT NULL DEFAULT now(), "updated" TIMESTAMP NOT NULL DEFAULT now(), "created_by" text NOT NULL, "updated_by" text NOT NULL, "class_name" text NOT NULL, "scope" text NOT NULL, "update_count" integer NOT NULL DEFAULT 0, "active" boolean NOT NULL DEFAULT true, "name" text NOT NULL, "comments" text NOT NULL DEFAULT '', "environment" text NOT NULL DEFAULT 'production', "serial_number" text DEFAULT '', "os" text, "companyGuid" uuid, "supportGroupGuid" uuid, "primaryOwnerGuid" uuid, "vendorGuid" uuid, "manufacturerGuid" uuid, CONSTRAINT "PK_f7b0c5e8f2972ed77642226895e" PRIMARY KEY ("guid"))`);
        await queryRunner.query(`CREATE INDEX "IDX_81f4e90e3bfc19c28534694fce" ON "cmdb"."ci" ("class_name") `);
        await queryRunner.query(`CREATE TABLE "core"."cost_centre" ("guid" uuid NOT NULL DEFAULT uuid_generate_v4(), "created" TIMESTAMP NOT NULL DEFAULT now(), "updated" TIMESTAMP NOT NULL DEFAULT now(), "created_by" text NOT NULL, "updated_by" text NOT NULL, "class_name" text NOT NULL, "scope" text NOT NULL, "update_count" integer NOT NULL DEFAULT 0, "active" boolean NOT NULL DEFAULT true, "name" text NOT NULL, "description" text NOT NULL DEFAULT '', "code" text NOT NULL, "centreHeadGuid" uuid, "departmentGuid" uuid, CONSTRAINT "PK_8c465c5b6a1be3d10e993f54cf2" PRIMARY KEY ("guid"))`);
        await queryRunner.query(`CREATE TABLE "core"."location" ("guid" uuid NOT NULL DEFAULT uuid_generate_v4(), "created" TIMESTAMP NOT NULL DEFAULT now(), "updated" TIMESTAMP NOT NULL DEFAULT now(), "created_by" text NOT NULL, "updated_by" text NOT NULL, "class_name" text NOT NULL, "scope" text NOT NULL, "update_count" integer NOT NULL DEFAULT 0, "active" boolean NOT NULL DEFAULT true, CONSTRAINT "PK_02cdd6eb9deca8bc381da3f77ff" PRIMARY KEY ("guid"))`);
        await queryRunner.query(`CREATE TABLE "core"."task" ("guid" uuid NOT NULL DEFAULT uuid_generate_v4(), "created" TIMESTAMP NOT NULL DEFAULT now(), "updated" TIMESTAMP NOT NULL DEFAULT now(), "created_by" text NOT NULL, "updated_by" text NOT NULL, "class_name" text NOT NULL, "scope" text NOT NULL, "update_count" integer NOT NULL DEFAULT 0, "active" boolean NOT NULL DEFAULT true, "summary" text NOT NULL DEFAULT '', "details" text NOT NULL DEFAULT '', "priority" integer NOT NULL DEFAULT 4, "assigneeGuid" uuid, "assignmentGroupGuid" uuid, "authorisedContactGuid" uuid, CONSTRAINT "PK_3347d13ab9755b8058b72b4a7b5" PRIMARY KEY ("guid"))`);
        await queryRunner.query(`CREATE TABLE "itsm"."itsm_task" ("guid" uuid NOT NULL DEFAULT uuid_generate_v4(), "created" TIMESTAMP NOT NULL DEFAULT now(), "updated" TIMESTAMP NOT NULL DEFAULT now(), "created_by" text NOT NULL, "updated_by" text NOT NULL, "class_name" text NOT NULL, "scope" text NOT NULL, "update_count" integer NOT NULL DEFAULT 0, "active" boolean NOT NULL DEFAULT true, "summary" text NOT NULL DEFAULT '', "details" text NOT NULL DEFAULT '', "priority" integer NOT NULL DEFAULT 4, "planned_start" date, "planned_finish" date, "justification" text DEFAULT '', "implementation_plan" text DEFAULT '', "backout_plan" text DEFAULT '', "test_plan" text DEFAULT '', "risk_analysis" text DEFAULT '', "impact" integer DEFAULT 4, "urgency" integer DEFAULT 4, "assigneeGuid" uuid, "assignmentGroupGuid" uuid, "authorisedContactGuid" uuid, "parentTaskGuid" uuid, "configItemGuid" uuid, "parentChangeGuid" uuid, "parentIncidentGuid" uuid, CONSTRAINT "PK_dbbfdd2dcb333a7697080fb1d1b" PRIMARY KEY ("guid"))`);
        await queryRunner.query(`CREATE INDEX "IDX_d5652aba78280f64f28843092b" ON "itsm"."itsm_task" ("class_name") `);
        await queryRunner.query(`CREATE TABLE "itsm"."sla_definition" ("guid" uuid NOT NULL DEFAULT uuid_generate_v4(), "created" TIMESTAMP NOT NULL DEFAULT now(), "updated" TIMESTAMP NOT NULL DEFAULT now(), "created_by" text NOT NULL, "updated_by" text NOT NULL, "class_name" text NOT NULL, "scope" text NOT NULL, "update_count" integer NOT NULL DEFAULT 0, "active" boolean NOT NULL DEFAULT true, "name" text NOT NULL, CONSTRAINT "PK_c3dfd7820faede2783c09c30e2d" PRIMARY KEY ("guid"))`);
        await queryRunner.query(`CREATE TABLE "itsm"."task_sla" ("guid" uuid NOT NULL DEFAULT uuid_generate_v4(), "created" TIMESTAMP NOT NULL DEFAULT now(), "updated" TIMESTAMP NOT NULL DEFAULT now(), "created_by" text NOT NULL, "updated_by" text NOT NULL, "class_name" text NOT NULL, "scope" text NOT NULL, "update_count" integer NOT NULL DEFAULT 0, "active" boolean NOT NULL DEFAULT true, "slaDefinitionGuid" uuid, CONSTRAINT "PK_8f53f0622602db730b8e999091a" PRIMARY KEY ("guid"))`);
        await queryRunner.query(`CREATE TABLE "system"."event" ("guid" uuid NOT NULL DEFAULT uuid_generate_v4(), "created" TIMESTAMP NOT NULL DEFAULT now(), "updated" TIMESTAMP NOT NULL DEFAULT now(), "created_by" text NOT NULL, "updated_by" text NOT NULL, "class_name" text NOT NULL, "scope" text NOT NULL, "update_count" integer NOT NULL DEFAULT 0, "active" boolean NOT NULL DEFAULT true, "name" text NOT NULL, "description" text NOT NULL, "table" text, CONSTRAINT "PK_e7d9ae883cf3a1a444721a29ca5" PRIMARY KEY ("guid"))`);
        await queryRunner.query(`CREATE TABLE "system"."event_action" ("guid" uuid NOT NULL DEFAULT uuid_generate_v4(), "created" TIMESTAMP NOT NULL DEFAULT now(), "updated" TIMESTAMP NOT NULL DEFAULT now(), "created_by" text NOT NULL, "updated_by" text NOT NULL, "class_name" text NOT NULL, "scope" text NOT NULL, "update_count" integer NOT NULL DEFAULT 0, "active" boolean NOT NULL DEFAULT true, "event_name" text NOT NULL, "script" text NOT NULL, CONSTRAINT "PK_8932069cb78487df985a686db24" PRIMARY KEY ("guid"))`);
        await queryRunner.query(`CREATE TYPE "system"."event_queue_entry_status_enum" AS ENUM('0', '1', '2', '3')`);
        await queryRunner.query(`CREATE TABLE "system"."event_queue_entry" ("guid" uuid NOT NULL DEFAULT uuid_generate_v4(), "created" TIMESTAMP NOT NULL DEFAULT now(), "updated" TIMESTAMP NOT NULL DEFAULT now(), "created_by" text NOT NULL, "updated_by" text NOT NULL, "class_name" text NOT NULL, "scope" text NOT NULL, "update_count" integer NOT NULL DEFAULT 0, "active" boolean NOT NULL DEFAULT true, "status" "system"."event_queue_entry_status_enum" NOT NULL DEFAULT '0', "message" text NOT NULL DEFAULT '', "parameters" json, "record" uuid, "eventGuid" uuid, CONSTRAINT "PK_4785c9cca357d1ff025dfadc0d7" PRIMARY KEY ("guid"))`);
        await queryRunner.query(`CREATE TABLE "system"."script_library" ("guid" uuid NOT NULL DEFAULT uuid_generate_v4(), "created" TIMESTAMP NOT NULL DEFAULT now(), "updated" TIMESTAMP NOT NULL DEFAULT now(), "created_by" text NOT NULL, "updated_by" text NOT NULL, "class_name" text NOT NULL, "scope" text NOT NULL, "update_count" integer NOT NULL DEFAULT 0, "active" boolean NOT NULL DEFAULT true, "name" text NOT NULL, "script" text NOT NULL, "description" text NOT NULL DEFAULT '', CONSTRAINT "PK_45830ddebbf0e46c48d71a97275" PRIMARY KEY ("guid"))`);
        await queryRunner.query(`CREATE TABLE "system"."ui_action" ("guid" uuid NOT NULL DEFAULT uuid_generate_v4(), "created" TIMESTAMP NOT NULL DEFAULT now(), "updated" TIMESTAMP NOT NULL DEFAULT now(), "created_by" text NOT NULL, "updated_by" text NOT NULL, "class_name" text NOT NULL, "scope" text NOT NULL, "update_count" integer NOT NULL DEFAULT 0, "active" boolean NOT NULL DEFAULT true, "name" text NOT NULL, "table" text NOT NULL DEFAULT 'global', "global" boolean NOT NULL DEFAULT false, "order" integer NOT NULL DEFAULT 100, "description" text NOT NULL DEFAULT '', "tooltip" text NOT NULL DEFAULT '', "form_button" boolean NOT NULL DEFAULT false, "form_context" boolean NOT NULL DEFAULT false, "form_link" boolean NOT NULL DEFAULT false, "list_button" boolean NOT NULL DEFAULT false, "list_context" boolean NOT NULL DEFAULT false, "list_link" boolean NOT NULL DEFAULT false, "client" boolean NOT NULL DEFAULT false, "server" boolean NOT NULL DEFAULT false, "client_script" text NOT NULL DEFAULT '', "server_script" text NOT NULL DEFAULT '', CONSTRAINT "PK_27fcb90fe72c12cc9a2a65a29dc" PRIMARY KEY ("guid"))`);
        await queryRunner.query(`CREATE TABLE "system"."acl_requires_role" ("aclGuid" uuid NOT NULL, "roleGuid" uuid NOT NULL, CONSTRAINT "PK_b7fa2c8e50232df0f97b6281b1b" PRIMARY KEY ("aclGuid", "roleGuid"))`);
        await queryRunner.query(`CREATE INDEX "IDX_db7d30d9a3045ce4ea883ca437" ON "system"."acl_requires_role" ("aclGuid") `);
        await queryRunner.query(`CREATE INDEX "IDX_bd8057b89be3779df9517a2124" ON "system"."acl_requires_role" ("roleGuid") `);
        await queryRunner.query(`CREATE TABLE "system"."user_has_role" ("userGuid" uuid NOT NULL, "roleGuid" uuid NOT NULL, CONSTRAINT "PK_4c380f028e6901a1fb97a6ee66a" PRIMARY KEY ("userGuid", "roleGuid"))`);
        await queryRunner.query(`CREATE INDEX "IDX_59a93e06bac9758f039e11745c" ON "system"."user_has_role" ("userGuid") `);
        await queryRunner.query(`CREATE INDEX "IDX_b784423b727a21f99184ad1087" ON "system"."user_has_role" ("roleGuid") `);
        await queryRunner.query(`CREATE TABLE "system"."group_membership" ("groupGuid" uuid NOT NULL, "userGuid" uuid NOT NULL, CONSTRAINT "PK_149e892ed0e7b59c47e2d531a25" PRIMARY KEY ("groupGuid", "userGuid"))`);
        await queryRunner.query(`CREATE INDEX "IDX_d9ae43821a1309a05fb2cc312e" ON "system"."group_membership" ("groupGuid") `);
        await queryRunner.query(`CREATE INDEX "IDX_b8c3f6ef73bff7165ef1438394" ON "system"."group_membership" ("userGuid") `);
        await queryRunner.query(`CREATE TABLE "system"."group_contains_role" ("groupGuid" uuid NOT NULL, "roleGuid" uuid NOT NULL, CONSTRAINT "PK_8536188fd1f3ad67b8885404600" PRIMARY KEY ("groupGuid", "roleGuid"))`);
        await queryRunner.query(`CREATE INDEX "IDX_cb5e9703f9d9cf94b47e7f9fdf" ON "system"."group_contains_role" ("groupGuid") `);
        await queryRunner.query(`CREATE INDEX "IDX_8c03f4535db932e0f31a215354" ON "system"."group_contains_role" ("roleGuid") `);
        await queryRunner.query(`CREATE TABLE "system"."ui_action_requires_role" ("uiActionGuid" uuid NOT NULL, "roleGuid" uuid NOT NULL, CONSTRAINT "PK_051ff5923aa3e2d6481f5f6afe4" PRIMARY KEY ("uiActionGuid", "roleGuid"))`);
        await queryRunner.query(`CREATE INDEX "IDX_bcb21d907b99a7005553f508bb" ON "system"."ui_action_requires_role" ("uiActionGuid") `);
        await queryRunner.query(`CREATE INDEX "IDX_79981067ab626c4987ef34e608" ON "system"."ui_action_requires_role" ("roleGuid") `);
        await queryRunner.query(`ALTER TABLE "system"."field_label" ADD CONSTRAINT "FK_67ee6cad272ef0709bd9ea744db" FOREIGN KEY ("elementGuid") REFERENCES "system"."dictionary"("guid") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "system"."acl" ADD CONSTRAINT "FK_5d59302fdf0e63c2efb13ed874b" FOREIGN KEY ("fieldGuid") REFERENCES "system"."dictionary"("guid") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "core"."department" ADD CONSTRAINT "FK_535f12599ac55d043d7b4253c78" FOREIGN KEY ("departmentHeadGuid") REFERENCES "system"."user"("guid") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "core"."department" ADD CONSTRAINT "FK_bd5fd495d9d40bd416d3bd24c7e" FOREIGN KEY ("companyGuid") REFERENCES "core"."company"("guid") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "system"."user" ADD CONSTRAINT "FK_9b4acca00abebb4c580fc6fbf7b" FOREIGN KEY ("departmentGuid") REFERENCES "core"."department"("guid") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "system"."user" ADD CONSTRAINT "FK_39d46f5408975b627f9a2125765" FOREIGN KEY ("companyGuid") REFERENCES "core"."company"("guid") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "system"."group" ADD CONSTRAINT "FK_24cb014529a631a05e7ec236274" FOREIGN KEY ("managerGuid") REFERENCES "system"."user"("guid") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "cmdb"."ci" ADD CONSTRAINT "FK_3d365d2c1a68bf65d6cec76f8ae" FOREIGN KEY ("companyGuid") REFERENCES "core"."company"("guid") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "cmdb"."ci" ADD CONSTRAINT "FK_5c4635ce265455db30fd6f1bd16" FOREIGN KEY ("supportGroupGuid") REFERENCES "system"."group"("guid") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "cmdb"."ci" ADD CONSTRAINT "FK_58489cd210bee88e92abe5a48ef" FOREIGN KEY ("primaryOwnerGuid") REFERENCES "system"."user"("guid") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "cmdb"."ci" ADD CONSTRAINT "FK_4bd87ad6b6c85cdb5c420efb8d2" FOREIGN KEY ("vendorGuid") REFERENCES "core"."company"("guid") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "cmdb"."ci" ADD CONSTRAINT "FK_23b25e4e18faf041801f51af4d7" FOREIGN KEY ("manufacturerGuid") REFERENCES "core"."company"("guid") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "core"."cost_centre" ADD CONSTRAINT "FK_520a58655864c5f6f0cce75422b" FOREIGN KEY ("centreHeadGuid") REFERENCES "system"."user"("guid") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "core"."cost_centre" ADD CONSTRAINT "FK_2782faa9ad3a7e7336628c32416" FOREIGN KEY ("departmentGuid") REFERENCES "core"."department"("guid") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "core"."task" ADD CONSTRAINT "FK_ccbcf31775c029a912a5d3c8d06" FOREIGN KEY ("assigneeGuid") REFERENCES "system"."user"("guid") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "core"."task" ADD CONSTRAINT "FK_e5d2ed696b1fcb77bb6e0eb0a66" FOREIGN KEY ("assignmentGroupGuid") REFERENCES "system"."group"("guid") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "core"."task" ADD CONSTRAINT "FK_fa711b887d374a0094e9cb699de" FOREIGN KEY ("authorisedContactGuid") REFERENCES "system"."user"("guid") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "itsm"."itsm_task" ADD CONSTRAINT "FK_86cd5094aa84f0ba9a61e64d7d5" FOREIGN KEY ("assigneeGuid") REFERENCES "system"."user"("guid") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "itsm"."itsm_task" ADD CONSTRAINT "FK_d52eb1cb1e460c7ea2d8f5f42fd" FOREIGN KEY ("assignmentGroupGuid") REFERENCES "system"."group"("guid") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "itsm"."itsm_task" ADD CONSTRAINT "FK_836b50e0e5869903f1179935503" FOREIGN KEY ("authorisedContactGuid") REFERENCES "system"."user"("guid") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "itsm"."itsm_task" ADD CONSTRAINT "FK_055be0f73c6ca8c7f8f84225c06" FOREIGN KEY ("parentTaskGuid") REFERENCES "itsm"."itsm_task"("guid") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "itsm"."itsm_task" ADD CONSTRAINT "FK_0ea87ce4bb22692d51eb6b9a11d" FOREIGN KEY ("configItemGuid") REFERENCES "cmdb"."ci"("guid") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "itsm"."itsm_task" ADD CONSTRAINT "FK_bc6174fb62539ac290ff717762b" FOREIGN KEY ("parentChangeGuid") REFERENCES "itsm"."itsm_task"("guid") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "itsm"."itsm_task" ADD CONSTRAINT "FK_994a7d849d304797401ae02d647" FOREIGN KEY ("parentIncidentGuid") REFERENCES "itsm"."itsm_task"("guid") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "itsm"."task_sla" ADD CONSTRAINT "FK_7de4f5ea4521c96202ec4d6002c" FOREIGN KEY ("slaDefinitionGuid") REFERENCES "itsm"."sla_definition"("guid") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "system"."event_queue_entry" ADD CONSTRAINT "FK_380b63a4cce01c8f43d6c1149f3" FOREIGN KEY ("eventGuid") REFERENCES "system"."event"("guid") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "system"."acl_requires_role" ADD CONSTRAINT "FK_db7d30d9a3045ce4ea883ca437f" FOREIGN KEY ("aclGuid") REFERENCES "system"."acl"("guid") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "system"."acl_requires_role" ADD CONSTRAINT "FK_bd8057b89be3779df9517a2124b" FOREIGN KEY ("roleGuid") REFERENCES "system"."role"("guid") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "system"."user_has_role" ADD CONSTRAINT "FK_59a93e06bac9758f039e11745c8" FOREIGN KEY ("userGuid") REFERENCES "system"."user"("guid") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "system"."user_has_role" ADD CONSTRAINT "FK_b784423b727a21f99184ad1087c" FOREIGN KEY ("roleGuid") REFERENCES "system"."role"("guid") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "system"."group_membership" ADD CONSTRAINT "FK_d9ae43821a1309a05fb2cc312ef" FOREIGN KEY ("groupGuid") REFERENCES "system"."group"("guid") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "system"."group_membership" ADD CONSTRAINT "FK_b8c3f6ef73bff7165ef14383944" FOREIGN KEY ("userGuid") REFERENCES "system"."user"("guid") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "system"."group_contains_role" ADD CONSTRAINT "FK_cb5e9703f9d9cf94b47e7f9fdf0" FOREIGN KEY ("groupGuid") REFERENCES "system"."group"("guid") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "system"."group_contains_role" ADD CONSTRAINT "FK_8c03f4535db932e0f31a215354e" FOREIGN KEY ("roleGuid") REFERENCES "system"."role"("guid") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "system"."ui_action_requires_role" ADD CONSTRAINT "FK_bcb21d907b99a7005553f508bb7" FOREIGN KEY ("uiActionGuid") REFERENCES "system"."ui_action"("guid") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "system"."ui_action_requires_role" ADD CONSTRAINT "FK_79981067ab626c4987ef34e6087" FOREIGN KEY ("roleGuid") REFERENCES "system"."role"("guid") ON DELETE CASCADE ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "system"."ui_action_requires_role" DROP CONSTRAINT "FK_79981067ab626c4987ef34e6087"`);
        await queryRunner.query(`ALTER TABLE "system"."ui_action_requires_role" DROP CONSTRAINT "FK_bcb21d907b99a7005553f508bb7"`);
        await queryRunner.query(`ALTER TABLE "system"."group_contains_role" DROP CONSTRAINT "FK_8c03f4535db932e0f31a215354e"`);
        await queryRunner.query(`ALTER TABLE "system"."group_contains_role" DROP CONSTRAINT "FK_cb5e9703f9d9cf94b47e7f9fdf0"`);
        await queryRunner.query(`ALTER TABLE "system"."group_membership" DROP CONSTRAINT "FK_b8c3f6ef73bff7165ef14383944"`);
        await queryRunner.query(`ALTER TABLE "system"."group_membership" DROP CONSTRAINT "FK_d9ae43821a1309a05fb2cc312ef"`);
        await queryRunner.query(`ALTER TABLE "system"."user_has_role" DROP CONSTRAINT "FK_b784423b727a21f99184ad1087c"`);
        await queryRunner.query(`ALTER TABLE "system"."user_has_role" DROP CONSTRAINT "FK_59a93e06bac9758f039e11745c8"`);
        await queryRunner.query(`ALTER TABLE "system"."acl_requires_role" DROP CONSTRAINT "FK_bd8057b89be3779df9517a2124b"`);
        await queryRunner.query(`ALTER TABLE "system"."acl_requires_role" DROP CONSTRAINT "FK_db7d30d9a3045ce4ea883ca437f"`);
        await queryRunner.query(`ALTER TABLE "system"."event_queue_entry" DROP CONSTRAINT "FK_380b63a4cce01c8f43d6c1149f3"`);
        await queryRunner.query(`ALTER TABLE "itsm"."task_sla" DROP CONSTRAINT "FK_7de4f5ea4521c96202ec4d6002c"`);
        await queryRunner.query(`ALTER TABLE "itsm"."itsm_task" DROP CONSTRAINT "FK_994a7d849d304797401ae02d647"`);
        await queryRunner.query(`ALTER TABLE "itsm"."itsm_task" DROP CONSTRAINT "FK_bc6174fb62539ac290ff717762b"`);
        await queryRunner.query(`ALTER TABLE "itsm"."itsm_task" DROP CONSTRAINT "FK_0ea87ce4bb22692d51eb6b9a11d"`);
        await queryRunner.query(`ALTER TABLE "itsm"."itsm_task" DROP CONSTRAINT "FK_055be0f73c6ca8c7f8f84225c06"`);
        await queryRunner.query(`ALTER TABLE "itsm"."itsm_task" DROP CONSTRAINT "FK_836b50e0e5869903f1179935503"`);
        await queryRunner.query(`ALTER TABLE "itsm"."itsm_task" DROP CONSTRAINT "FK_d52eb1cb1e460c7ea2d8f5f42fd"`);
        await queryRunner.query(`ALTER TABLE "itsm"."itsm_task" DROP CONSTRAINT "FK_86cd5094aa84f0ba9a61e64d7d5"`);
        await queryRunner.query(`ALTER TABLE "core"."task" DROP CONSTRAINT "FK_fa711b887d374a0094e9cb699de"`);
        await queryRunner.query(`ALTER TABLE "core"."task" DROP CONSTRAINT "FK_e5d2ed696b1fcb77bb6e0eb0a66"`);
        await queryRunner.query(`ALTER TABLE "core"."task" DROP CONSTRAINT "FK_ccbcf31775c029a912a5d3c8d06"`);
        await queryRunner.query(`ALTER TABLE "core"."cost_centre" DROP CONSTRAINT "FK_2782faa9ad3a7e7336628c32416"`);
        await queryRunner.query(`ALTER TABLE "core"."cost_centre" DROP CONSTRAINT "FK_520a58655864c5f6f0cce75422b"`);
        await queryRunner.query(`ALTER TABLE "cmdb"."ci" DROP CONSTRAINT "FK_23b25e4e18faf041801f51af4d7"`);
        await queryRunner.query(`ALTER TABLE "cmdb"."ci" DROP CONSTRAINT "FK_4bd87ad6b6c85cdb5c420efb8d2"`);
        await queryRunner.query(`ALTER TABLE "cmdb"."ci" DROP CONSTRAINT "FK_58489cd210bee88e92abe5a48ef"`);
        await queryRunner.query(`ALTER TABLE "cmdb"."ci" DROP CONSTRAINT "FK_5c4635ce265455db30fd6f1bd16"`);
        await queryRunner.query(`ALTER TABLE "cmdb"."ci" DROP CONSTRAINT "FK_3d365d2c1a68bf65d6cec76f8ae"`);
        await queryRunner.query(`ALTER TABLE "system"."group" DROP CONSTRAINT "FK_24cb014529a631a05e7ec236274"`);
        await queryRunner.query(`ALTER TABLE "system"."user" DROP CONSTRAINT "FK_39d46f5408975b627f9a2125765"`);
        await queryRunner.query(`ALTER TABLE "system"."user" DROP CONSTRAINT "FK_9b4acca00abebb4c580fc6fbf7b"`);
        await queryRunner.query(`ALTER TABLE "core"."department" DROP CONSTRAINT "FK_bd5fd495d9d40bd416d3bd24c7e"`);
        await queryRunner.query(`ALTER TABLE "core"."department" DROP CONSTRAINT "FK_535f12599ac55d043d7b4253c78"`);
        await queryRunner.query(`ALTER TABLE "system"."acl" DROP CONSTRAINT "FK_5d59302fdf0e63c2efb13ed874b"`);
        await queryRunner.query(`ALTER TABLE "system"."field_label" DROP CONSTRAINT "FK_67ee6cad272ef0709bd9ea744db"`);
        await queryRunner.query(`DROP INDEX "system"."IDX_79981067ab626c4987ef34e608"`);
        await queryRunner.query(`DROP INDEX "system"."IDX_bcb21d907b99a7005553f508bb"`);
        await queryRunner.query(`DROP TABLE "system"."ui_action_requires_role"`);
        await queryRunner.query(`DROP INDEX "system"."IDX_8c03f4535db932e0f31a215354"`);
        await queryRunner.query(`DROP INDEX "system"."IDX_cb5e9703f9d9cf94b47e7f9fdf"`);
        await queryRunner.query(`DROP TABLE "system"."group_contains_role"`);
        await queryRunner.query(`DROP INDEX "system"."IDX_b8c3f6ef73bff7165ef1438394"`);
        await queryRunner.query(`DROP INDEX "system"."IDX_d9ae43821a1309a05fb2cc312e"`);
        await queryRunner.query(`DROP TABLE "system"."group_membership"`);
        await queryRunner.query(`DROP INDEX "system"."IDX_b784423b727a21f99184ad1087"`);
        await queryRunner.query(`DROP INDEX "system"."IDX_59a93e06bac9758f039e11745c"`);
        await queryRunner.query(`DROP TABLE "system"."user_has_role"`);
        await queryRunner.query(`DROP INDEX "system"."IDX_bd8057b89be3779df9517a2124"`);
        await queryRunner.query(`DROP INDEX "system"."IDX_db7d30d9a3045ce4ea883ca437"`);
        await queryRunner.query(`DROP TABLE "system"."acl_requires_role"`);
        await queryRunner.query(`DROP TABLE "system"."ui_action"`);
        await queryRunner.query(`DROP TABLE "system"."script_library"`);
        await queryRunner.query(`DROP TABLE "system"."event_queue_entry"`);
        await queryRunner.query(`DROP TYPE "system"."event_queue_entry_status_enum"`);
        await queryRunner.query(`DROP TABLE "system"."event_action"`);
        await queryRunner.query(`DROP TABLE "system"."event"`);
        await queryRunner.query(`DROP TABLE "itsm"."task_sla"`);
        await queryRunner.query(`DROP TABLE "itsm"."sla_definition"`);
        await queryRunner.query(`DROP INDEX "itsm"."IDX_d5652aba78280f64f28843092b"`);
        await queryRunner.query(`DROP TABLE "itsm"."itsm_task"`);
        await queryRunner.query(`DROP TABLE "core"."task"`);
        await queryRunner.query(`DROP TABLE "core"."location"`);
        await queryRunner.query(`DROP TABLE "core"."cost_centre"`);
        await queryRunner.query(`DROP INDEX "cmdb"."IDX_81f4e90e3bfc19c28534694fce"`);
        await queryRunner.query(`DROP TABLE "cmdb"."ci"`);
        await queryRunner.query(`DROP TABLE "system"."group"`);
        await queryRunner.query(`DROP TABLE "system"."user"`);
        await queryRunner.query(`DROP TABLE "core"."department"`);
        await queryRunner.query(`DROP TABLE "system"."role"`);
        await queryRunner.query(`DROP TABLE "system"."acl"`);
        await queryRunner.query(`DROP TABLE "core"."company"`);
        await queryRunner.query(`DROP TABLE "system"."dbo"`);
        await queryRunner.query(`DROP TABLE "system"."server_script"`);
        await queryRunner.query(`DROP TABLE "system"."dictionary"`);
        await queryRunner.query(`DROP TABLE "system"."field_label"`);
    }

}
